// import { ChainId } from '@pancakeswap-libs/sdk';
import { Configuration } from './tomb-finance/config';
import { BankInfo } from './tomb-finance';
import { ChainId } from '@uniswap/sdk';

const configurations: { [env: string]: Configuration } = {
  production: {
    chainId: 8453 as ChainId,
    networkName: 'Base Mainnet',
    ftmscanUrl: 'https://basescan.org',
    defaultProvider: 'https://mainnet.base.org',
    deployments: require('./tomb-finance/deployments/deployments.mainnet.json'),
    externalTokens: {
      // CHANGE THSE
      TOMBSHI: ['0xdBEc1002Ec811dc071bC9791fbbcd8863c6Edfc3', 18],
      TOSHARE: ['0xf7d9B66208feE4aCf300b9fAC1822A415e273e1C', 18],
      TOSHBOND: ['0xae777A2EE026bB79F11c32502983cd03dF36E320', 18],
      'TOMBSHI-TOSHI-LP': ['0x56fb9d8c3c84dd0c4bb59a157e24a882ddab519a', 18],
      'TOSHARE-ETH-LP': ['0x03d15E0451e54Eec95ac5AcB5B0a7ce69638c62A', 18],
      ETH: ['0x0000000000000000000000000000000000000000', 18],
      WETH: ['0x4200000000000000000000000000000000000006', 18],
      OGRE: ['0xAB8a1c03b8E4e1D21c8Ddd6eDf9e07f26E843492', 18],
      TOSHI: ['0x8544FE9D190fD7EC52860abBf45088E81Ee24a8c', 18],
      USDBC: ['0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA', 6],
      AXLUSDBC: ['0xEB466342C4d449BC9f53A865D5Cb90586f405215', 6],

      // NOT THESE
      SNOBOND: ['0x8aB4Ac266d8e698b7E39f97Ec17876076680f6f1', 18],
      FOX: ['0xFFffFfFf68A2e13F7B68d2E190E37D804E02E0ad', 18],
      DIBS: ['0x5E430F88D1BE82EB3eF92b6fF06125168fD5DCf2', 18],
      USDIBS: ['0x0EfA5328FEfCe96C8d10661bd97403764D477853', 18],
      GRAPE: ['0x5541D83EFaD1f281571B343977648B75d95cdAC2', 18],
      JOE: ['0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd', 18],
      MIM: ['0x130966628846BFd36ff31a822705796e8cb8C18D', 18],
      'GRAPE-TOMBSHI-LP': ['0xA3F24b18608606079a0317Cbe6Cda54CED931420', 18],
      'USDC-WAVAX-LP': ['0xA389f9430876455C36478DeEa9769B7Ca4E3DDB1', 18],
      'USDC-JOE-LP': ['0x67926d973cD8eE876aD210fAaf7DFfA99E414aCf', 18],
      'SNO-JOE-LP': ['0xe63b66a8cf7811525cd15dab15f17fb62aa5af2f', 18],
      'MIM-WAVAX-LP': ['0x781655d802670bbA3c89aeBaaEa59D3182fD755D', 18],
      'TOMBSHI-USDIBS-LP': ['0x26E6E2CbE80A7408573BE67578ee5c10F2984f99', 18],
      YUSD: ['0x111111111111ed1D73f860F57b2798b683f2d325', 18],
      NRWL: ['0x501012893eE88976AB8B5289B7a78E307d5d9DCb', 18],
      NBOND: ['0x0e0D542Dc4973CabE3Aa769aCdC69Ce5dE812513', 18],
      'NRWL-YUSD-LP': ['0xE4f4f9DD9cD45bC44FD517f4AE490591030274F6', 18],
      XWLRS: ['0x2dc3Bb328000553D1D64ec1BEF00572F62B5Ec7C', 18],
    },
    baseLaunchDate: new Date('2022-05-14T18:00:00Z'),
    bondLaunchesAt: new Date('2022-05-15T09:00:00Z'),
    masonryLaunchesAt: new Date('2022-05-15T09:00:00Z'),
    nrwlLaunchDate: new Date('2022-07-24T14:00:00Z'),
    nrwlBoardroomLaunchDate: new Date('2022-07-27T14:00:00Z'),
    refreshInterval: 10000,
  },
};

export const bankDefinitions: { [contractName: string]: BankInfo } = {
  /*
  Explanation:
  name: description of the card
  poolId: the poolId assigned in the contract
  sectionInUI: way to distinguish in which of the 3 pool groups it should be listed
        - 0 = Single asset stake pools
        - 1 = LP asset staking rewarding TOMB
        - 2 = LP asset staking rewarding TSHARE
  contract: the contract name which will be loaded from the deployment.environmnet.json
  depositTokenName : the name of the token to be deposited
  earnTokenName: the rewarded token
  finished: will disable the pool on the UI if set to true
  sort: the order of the pool
  */

  // ethGenesisRewardPool: {
  //   name: 'Earn TOMBSHI by ETH',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'ethGenesisRewardPool',
  //   depositTokenName: 'ETH',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 1,
  //   closedForStaking: false,
  // },
  // ogreGenesisRewardPool: {
  //   name: 'Earn TOMBSHI by OGRE',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'ogreGenesisRewardPool',
  //   depositTokenName: 'OGRE',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 2,
  //   closedForStaking: false,
  // },
  // toshiGenesisRewardPool: {
  //   name: 'Earn TOMBSHI by TOSHI',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'toshiGenesisRewardPool',
  //   depositTokenName: 'TOSHI',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 3,
  //   closedForStaking: false,
  // },
  TombshiGenesisRewardPool: {
    name: 'Earn TOMBSHI by TOMBSHI-TOSHI-LP',
    poolId: 0,
    sectionInUI: 0,
    contract: 'TombshiGenesisRewardPool',
    depositTokenName: 'TOMBSHI-TOSHI-LP',
    earnTokenName: 'TOMBSHI',
    finished: false,
    sort: 4,
    closedForStaking: false,
  },
  // tombshitoshiGenesisRewardPool: {
  //   name: 'Earn TOMBSHI by TOMBSHI-TOSHI-LP',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'tombshitoshiGenesisRewardPool',
  //   depositTokenName: 'TOMBSHI-TOSHI-LP',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 5,
  //   closedForStaking: false,
  // },
  // toshareethGenesisRewardPool: {
  //   name: 'Earn TOMBSHI by TOSHARE-ETH-LP',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'toshareethGenesisRewardPool',
  //   depositTokenName: 'TOSHARE-ETH-LP',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 6,
  //   closedForStaking: false,
  // },
  // usdbCGenesisRewardPool: {
  //   name: 'Earn TOMBSHI by USDBC',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'usdbCGenesisRewardPool',
  //   depositTokenName: 'USDBC',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 7,
  //   closedForStaking: false,
  // },
  // axlUsdbCGenesisRewardPool: {
  //   name: 'Earn TOMBSHI by AXLUSDBC',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'axlUsdbCGenesisRewardPool',
  //   depositTokenName: 'AXLUSDBC',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 8,
  //   closedForStaking: false,
  // },

  // WlrsUsdcLPWShareRewardPool: {
  //   name: 'Earn TOSHARE by TOMBSHI-USDC.e LP',
  //   poolId: 0,
  //   sectionInUI: 0,
  //   contract: 'WlrsUsdcLPWShareRewardPool',
  //   depositTokenName: 'TOMBSHI-USDC-LP',
  //   earnTokenName: 'TOSHARE',
  //   finished: false,
  //   sort: 1,
  //   closedForStaking: false,
  // },
  // WShareUsdcLPWShareRewardPool: {
  //   name: 'Earn TOSHARE by TOSHARE-USDC.e LP',
  //   poolId: 1,
  //   sectionInUI: 2,
  //   contract: 'WShareUsdcLPWShareRewardPool',
  //   depositTokenName: 'TOSHARE-USDC-LP',
  //   earnTokenName: 'TOSHARE',
  //   finished: false,
  //   sort: 2,
  //   closedForStaking: false,
  // },
  // WlrsUSDibsLPWShareRewardPool: {
  //   name: 'Earn TOSHARE by TOMBSHI-USDibs LP',
  //   poolId: 3,
  //   sectionInUI: 2,
  //   contract: 'WlrsUSDibsLPWShareRewardPool',
  //   depositTokenName: 'TOMBSHI-USDIBS-LP',
  //   earnTokenName: 'TOSHARE',
  //   finished: false,
  //   sort: 3,
  //   closedForStaking: false,
  // },
  // NrwlYusdLPWShareRewardPool: {
  //   name: 'Earn TOSHARE by NRWL-YUSD LP',
  //   poolId: 4,
  //   sectionInUI: 2,
  //   contract: 'NrwlYusdLPWShareRewardPool',
  //   depositTokenName: 'NRWL-YUSD-LP',
  //   earnTokenName: 'TOSHARE',
  //   finished: false,
  //   sort: 4,
  //   closedForStaking: false,
  // },
  // WBondWShareRewardPool: {
  //   name: 'Earn TOSHARE with TOSHBOND',
  //   poolId: 6,
  //   sectionInUI: 0,
  //   contract: 'WBondWShareRewardPool',
  //   depositTokenName: 'TOSHBOND',
  //   earnTokenName: 'TOSHARE',
  //   finished: false,
  //   sort: 5,
  //   closedForStaking: false,
  // },
  // XWLRSShareRewardPool: {
  //   name: 'Earn TOSHARE with XWLRS',
  //   poolId: 7,
  //   sectionInUI: 0,
  //   contract: 'XWLRSShareRewardPool',
  //   depositTokenName: 'XWLRS',
  //   earnTokenName: 'TOSHARE',
  //   finished: false,
  //   sort: 6,
  //   closedForStaking: false,
  // },
  // WShareUSDCWLRSRewardPool: {
  //   name: 'Earn TOMBSHI with TOSHARE-USDC-LP',
  //   poolId: 8,
  //   sectionInUI: 0,
  //   contract: 'WShareUSDCWLRSRewardPool',
  //   depositTokenName: 'TOSHARE-USDC-LP',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 7,
  //   closedForStaking: false,
  // },
  /*WlrsUsdcLPRebate: {
    name: 'Bond TOMBSHI-USDC-LP for TOMBSHI',
    poolId: 100,
    sectionInUI: 3,
    contract: 'RebateTreasury',
    depositTokenName: 'TOMBSHI-USDC-LP',
    earnTokenName: 'TOMBSHI',
    finished: false,
    sort: 1,
    closedForStaking: false,
  },
  WShareUsdcJoeLPRebate: {
    name: 'Bond TOSHARE-USDC-LP for TOMBSHI',
    poolId: 100,
    sectionInUI: 3,
    contract: 'RebateTreasury',
    depositTokenName: 'TOSHARE-USDC-LP',
    earnTokenName: 'TOMBSHI',
    finished: false,
    sort: 2,
    closedForStaking: false,
  },*/
  // AvaxJoeLPRebate: {
  //   name: 'Bond AVAX for TOMBSHI',
  //   poolId: 100,
  //   sectionInUI: 3,
  //   contract: 'RebateTreasury',
  //   depositTokenName: 'WAVAX',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 3,
  //   closedForStaking: false,
  // },
  // UsdcJoeLPRebate: {
  //   name: 'Bond USDC.e for TOMBSHI',
  //   poolId: 100,
  //   sectionInUI: 3,
  //   contract: 'RebateTreasury',
  //   depositTokenName: 'USDC',
  //   earnTokenName: 'TOMBSHI',
  //   finished: false,
  //   sort: 4,
  //   closedForStaking: false,
  // },
  // PegLPNode: {
  //   name: 'Generate TOMBSHI-USDC LP with Nodes',
  //   poolId: 0,
  //   sectionInUI: 4,
  //   contract: 'PegLPNode',
  //   depositTokenName: 'TOMBSHI-USDC-LP',
  //   earnTokenName: 'TOMBSHI-USDC-LP',
  //   finished: false,
  //   sort: 6,
  //   closedForStaking: false,
  // },
  // ShareLPNode: {
  //   name: 'Generate TOSHARE-USDC LP with Nodes',
  //   poolId: 0,
  //   sectionInUI: 4,
  //   contract: 'ShareLPNode',
  //   depositTokenName: 'TOSHARE-USDC-LP',
  //   earnTokenName: 'TOSHARE-USDC-LP',
  //   finished: false,
  //   sort: 6,
  //   closedForStaking: false,
  // },
  // LPWlrsNode: {
  //   name: 'Generate GRAPE-TOMBSHI LP with Nodes',
  //   poolId: 0,
  //   sectionInUI: 4,
  //   contract: 'LPWlrsNode',
  //   depositTokenName: 'GRAPE-TOMBSHI-LP',
  //   earnTokenName: 'GRAPE-TOMBSHI-LP',
  //   finished: false,
  //   sort: 2,
  //   closedForStaking: false,
  // },
  // LPNrwlNode: {
  //   name: 'Generate NRWL-YUSD LP with Nodes',
  //   poolId: 0,
  //   sectionInUI: 4,
  //   contract: 'LPNrwlNode',
  //   depositTokenName: 'NRWL-YUSD-LP',
  //   earnTokenName: 'NRWL-YUSD-LP',
  //   finished: false,
  //   sort: 2,
  //   closedForStaking: false,
  // },
  // NrwlYusdGenesisNrwlRewardPool: {
  //   name: 'Earn NRWL by NRWL-YUSD LP',
  //   poolId: 0,
  //   sectionInUI: 5,
  //   contract: 'NrwlYusdGenesisNrwlRewardPool',
  //   depositTokenName: 'NRWL-YUSD-LP',
  //   earnTokenName: 'NRWL',
  //   finished: false,
  //   sort: 1,
  //   closedForStaking: false,
  // },
  // WlrsUsdcGenesisNrwlRewardPool: {
  //   name: 'Earn NRWL by TOMBSHI-USDC.e LP',
  //   poolId: 0,
  //   sectionInUI: 5,
  //   contract: 'WlrsUsdcGenesisNrwlRewardPool',
  //   depositTokenName: 'TOMBSHI-USDC-LP',
  //   earnTokenName: 'NRWL',
  //   finished: false,
  //   sort: 2,
  //   closedForStaking: false,
  // },
  // WshareUsdcGenesisNrwlRewardPool: {
  //   name: 'Earn NRWL by TOSHARE-USDC.e LP',
  //   poolId: 0,
  //   sectionInUI: 5,
  //   contract: 'WshareUsdcGenesisNrwlRewardPool',
  //   depositTokenName: 'TOSHARE-USDC-LP',
  //   earnTokenName: 'NRWL',
  //   finished: false,
  //   sort: 3,
  //   closedForStaking: false,
  // },
  // WshareGenesisNrwlRewardPool: {
  //   name: 'Earn NRWL by TOSHARE',
  //   poolId: 0,
  //   sectionInUI: 5,
  //   contract: 'WshareGenesisNrwlRewardPool',
  //   depositTokenName: 'TOSHARE',
  //   earnTokenName: 'NRWL',
  //   finished: false,
  //   sort: 4,
  //   closedForStaking: false,
  // },
};

export default configurations[/*process.env.NODE_ENV || */ 'production'];
